name: QuickShops
version: ${project.version}
description: Genesis Addon - Create fancy shops with minimal effort
authors: [Black_ixx, VoidEdge]
website: https://void.travja.dev
main: studio.magemonkey.genesis.addon.quickshops.QuickShops
depend: [Genesis]